[package]
name = "genomes"
version = "0.0.1"

publish = false

[dependencies]
rocket = "0.4.0"
rust-htslib = "*"
bit-vec = "*"
rustc-serialize = "0.3"
rocket_contrib = "*"
serde = { version = "1.0", features = ["derive"] }
rocket_cors = "0.5.0-beta-1"
bio = "*"

